services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:0-18     
    volumes:
      - .:/workspaces/nestjs-interview
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_DATABASE=nestjs_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - nestjs-network

  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nestjs_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nestjs_db"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge

volumes:
  postgres_data:
